Fix: Fix issue with Docker
GeraAlcantara/pinchef pull request #3
Opened 2021-10-06 17:09 UTC by SergioRibera

- Problema al buildear Docker arreglado
- Instrucciones agregadas al Readme

### TODO
- [x] Script para correr y buildear Docker automaticamente (In progress)
- [x] Arreglar problemas al correr la imagen (docker-compose arreglado)

2021-10-06 18:16 UTC, GeraAlcantara commented
Hola @SergioRibera 

Si me falto poner lo de como iniciar el docker container
Seguramente tendrán algunos problemas por la falta de un .env 

Uso pipenv para el manejo de las dependencias que tenia de mas porque estaba haciendo toda la documentación de FastAPI y algunas no se utilizan talvez con las que pusiste en los requerimiento sean suficientes. 

esto es lo que deberia llevar el .env file 

lo cual se debería de modificar manual mente y poner una base de ejemplo 

DB_USER={username}
DB_PASSWORD={password}
DB_NAME={db_name}
PGADMIN_DEFAULT_EMAIL={email}
PGADMIN_DEFAULT_PASSWORD={password}
DB_VOLUME={volume_name}
SQLALCHEMY_DATABASE_URL2 = sqlite:///./{db_name}.db
SQLALCHEMY_DATABASE_URL = postgresql+psycopg2://{username}:{password}@db:5432/{db_name}


Trate de correr la PR que enviaste pero no corrió el contenedor 

Tal vez esto te pueda ayudar a hacer las modificaciones a la PR 

Muchas gracias por pasarte al repositorio

2021-10-06 18:27 UTC, GeraAlcantara requested changes
se utiliza pipenv para crear el vitualenv 
se deberia de mantener el pipfile y pipfile.lock

2021-10-06 19:51 UTC, SergioRibera commented
Perfecto, ahora voy a hacer los cambios necesarios para que pueda correr

2021-10-07 03:45 UTC, SergioRibera commented
Clases separadas por archivos, testeado en Docker y la aplicacion carga correctamente

2021-10-07 19:15 UTC, merged

2021-10-10 17:36 UTC, GeraAlcantara commented
@all-contributors please add @SergioRibera for code